name: Trigger-demo
#run-name: 
on: workflow_dispatch
jobs:
  checkout1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "checking out the code."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "creating a new file."
      - name: List files in the repository
        run: |
          ls -ltr
      - run: echo "This job's status is."
