name: Trigger Build if a PR is closed
on:
  pull_request:
    types: [closed]

jobs:
  triggerBuildkite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: trigger on closed PR
      run: echo "PR is done"
